### ISSUE TITLE
The touch screen is rotated but the image on the screen is not.

### ISSUE THREAD

**Issue by gameme10** [balenablocks/fbcp#12]
Hi, I have a little problem.
The screen has the axis of the touch reversed when I have it in "display_rotate = 0" but when I have "display_rotate = 1" it doesn't happen but I want it in "display_rotate = 0".

I have given permission to support for accesing my device.

I'm sorry if my English is not very good but it is because I live in Spain and I don't know much English and I am using google translator

**Comment by zwhitchcox** [comment]
Hey, so this is more of a support issue...the support agents won't see this unless you post on the forums.

Would you mind reposting this to https://forums.balena.io/ ?

**Comment by gameme10** [comment]
> Hey, so this is more of a support issue...the support agents won't see this unless you post on the forums.
> 
> Would you mind reposting this to https://forums.balena.io/ ?

Okay, i will later continue. @zwhitchcox
