### ISSUE TITLE
use with custom dtoverlay (rotate, speed, fps)

### ISSUE THREAD

**Issue by klutchell** [balenablocks/fbcp#2]
How should I support a screen where I also have custom dtoverlay values?

`RESIN_HOST_CONFIG_dtoverlay=pitft35-resistive,rotate=90,speed=25000000,fps=20`

I got as far as using the generic `balenablocks/fbcp` and setting `FBCP_DISPLAY=pitft35-resistive` but I'm not sure how to achieve my other settings? Or is it expected to have both the device config and the env var set?

I realized that the balena-pihole repo currently does not have any instructions for enabling screens (intentionally) and just links to a related blog post. If I can figure out how to use this block I may just link to this repo instead :)

**Comment by klutchell** [comment]
I guess `RESIN_HOST_CONFIG_display_rotate` and similar vars may be of some help as documented here.

https://www.raspberrypi.org/documentation/configuration/config-txt/video.md

Does the dtoverlay at the device level need to be set at all if `FBCP_DISPLAY=pitft35-resistive` is set?

**Comment by klutchell** [comment]
@rahul-thakoor in case you are not watching this repo :)

**Comment by rahul-thakoor** [comment]
hey @klutchell 

> Does the dtoverlay at the device level need to be set at all if FBCP_DISPLAY=pitft35-resistive is set?

the fbcp driver used here does not utilize the [notro/fbtft](https://github.com/notro/fbtft) framebuffer driver.


so the dtoverlay should not be set.

you should be able to use the configs documented in https://www.raspberrypi.org/documentation/configuration/config-txt/video.md to achieve the rotation
