### ISSUE TITLE
RPi4 needs default DT overlay

### ISSUE THREAD

**Issue by phil-d-wilson** [balenablocks/fbcp#6]
RPi4 displays nothing on my Adafruit 2.8" TFT, until I set the DT overlay back to "vc4-fkms-v3d".

Should we detect the device type and twiddle the overlay if it's a Pi4 @rahul-thakoor ?

**Comment by phil-d-wilson** [comment]
https://github.com/juj/fbcp-ili9341/issues/75

**Comment by rahul-thakoor** [comment]
@phil-d-wilson afaik pi4 had `vc4-fkms-v3d` enforced? has this changed in recent os versions?

**Comment by phil-d-wilson** [comment]
@rahul-thakoor the block changed it to a TFT specific overlay

**Comment by rahul-thakoor** [comment]
hey @phil-d-wilson i am unable to reproduce this. Here is what I tried:

- provision a pi4 in a new app
- confirmed that `vc4-fkms-v3d` is set
- deployed `fbcp` and set minimum config to get it to work (`gpu_mem=64` and `hdmi_force_hotplug=1`)

`fbcp` does not set any dtoverlay automatically afaik. Can you confirm that you didn't test this on a device where dtoverlay was changed previously

**Comment by phil-d-wilson** [comment]
@rahul-thakoor I can't - since I have no memory. :)

I think the dtoverlay was set to something very TFT specific, so assumed it had been set by the block. However looking at the code, I can see that's not the case. Sorry for the hassle - happy to close. :)

**Comment by rahul-thakoor** [comment]
ok thanks for the feedback @phil-d-wilson :)
